/** Cap SPI re-export for catalog implementations; runtime services (core, test-kit) import the SPI from `@watchdog/caps/sdk`. */
export {
  defineCapability,
  DEFAULT_CAP_TIMEOUT_MS,
  capTimeoutMs,
  toCapDescriptor,
  type CapArtifact,
  type CapContext,
  type CapCredentialSpec,
  type CapDescriptor,
  type CapEgress,
  type CapFlag,
  type CapIoKind,
  type CapInterpretResult,
  type CapInterpretOpts,
  type CapJobPolicy,
  type CapKind,
  type CapRunResult,
  type CapabilityDef,
  type JsonObject,
  type PatchOp,
} from "./sdk";
export {
  CAPABILITIES,
  requireCapability,
  listCapabilities,
  capTimeoutCeilingMs,
} from "./registry";
export {
  PLAYBOOKS,
  listPlaybooks,
  listPlaybookDescriptors,
  requirePlaybook,
  planPlaybook,
  toPlaybookDescriptor,
  checkPlaybookAvailability,
  checkCapabilityAvailability,
  formatPlanError,
  derivePlaybookRequires,
  type PlaybookDef,
  type PlaybookDescriptor,
  type PlaybookPlan,
  type PlannedStep,
  type PlanError,
  type PlaybookSeedKind,
  type SeedValues,
  type PlaybookRequires,
  type CapabilityRequires,
  type AvailabilityError,
  type AvailabilityResult,
  hostFromUrl,
  isPlanError,
  materializeBoundInput,
  materializeFanOutInputs,
  normalizePlaybookStep,
  playbookCapabilityIds,
  predecessorFromJob,
  seedValuesToCandidateInput,
  seedValuesFromJson,
  seedValuesToJson,
  decidePlaybookAdvance,
  type PlaybookAdvance,
  type PlaybookJobView,
  type BindBag,
  type JobHandoff,
  type PlaybookStepDef,
  type PredecessorJob,
} from "./playbooks";
export {
  draftToPatchOps,
  draftToOutcome,
  type DraftToPatchOpsCtx,
  type ProcessCapOutcome,
} from "./evidence/lib/draft-to-patch-ops";
export { harvestDeterministic } from "./evidence/harvest/harvest";
export {
  KNOWN_CREDENTIALS,
  listKnownCredentials,
  type KnownCredential,
} from "./known-credentials";
