/**
 * Export a minified oRPC contract (+ OpenAPI JSON + AppRouter type entry)
 * for @watchdog/contract / @watchdog/client.
 * Run: pnpm --filter @watchdog/api export-contract
 */
import { writeFileSync } from "node:fs";
import path from "node:path";

import { exportContract } from "../src/export-contract.ts";

const here = import.meta.dirname;
const outDir = path.join(here, "../../contract/src/generated");
await exportContract(outDir);

const appRouterEntry = `/**
 * @generated by \`pnpm generate:client\` (\`@watchdog/api\` export-contract).
 * Do not edit by hand.
 *
 * Client-facing AppRouter alias. Procedure I/O types still come from the live
 * API router (minify strips Zod from JSON). This file is the only AppRouter
 * export for \`@watchdog/client\` so that package has no \`@watchdog/api\`
 * dependency. Relative path stays monorepo-local until a contract-first router
 * becomes the type SoT.
 */
export type { AppRouter } from "../../../api/src/router.ts";
`;
writeFileSync(path.join(outDir, "app-router.ts"), appRouterEntry);

console.log(`Wrote ${outDir}/contract.json`);
console.log(`Wrote ${outDir}/openapi.json`);
console.log(`Wrote ${outDir}/app-router.ts`);
